export const transactions = [
  {
    id: "trx-1",
    initial: "GJ",
    title: "Gaji Bulanan",
    date: "26 Mei 2026",
    category: "Payroll",
    amount: "+Rp 8.500.000",
  },
  {
    id: "trx-2",
    initial: "TF",
    title: "Transfer ke Dinda",
    date: "25 Mei 2026",
    category: "Transfer",
    amount: "-Rp 1.250.000",
  },
  {
    id: "trx-3",
    initial: "PL",
    title: "Pembayaran PLN",
    date: "24 Mei 2026",
    category: "Tagihan",
    amount: "-Rp 420.000",
  },
  {
    id: "trx-4",
    initial: "MK",
    title: "Top up Marketplace",
    date: "23 Mei 2026",
    category: "Belanja",
    amount: "-Rp 890.000",
  },
  {
    id: "trx-5",
    initial: "IN",
    title: "Refund Asuransi",
    date: "22 Mei 2026",
    category: "Refund",
    amount: "+Rp 350.000",
  },
  {
    id: "trx-6",
    initial: "SP",
    title: "Pembayaran Spotify",
    date: "21 Mei 2026",
    category: "Langganan",
    amount: "-Rp 54.990",
  },
];
